first iteration
mkrshv/todo-final-project pull request #1
Opened 2024-10-21 09:45 UTC by mkrshv

Добавлен весь функционал
Задачки со звездочкой в следующей итерации

2024-10-21 22:13 UTC, dirtymew requested changes
Привет Максим

хорошая работа - отличная структура и архитектура решения

есть что поправить и улучшить - жду правок и задания со звездочкой

2024-10-21 22:13 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write([]byte(nextDt))
ошибка не обработана - стоит ее залогировать

2024-10-21 22:13 UTC, dirtymew commented on handlers/handlers.go
> +	w.Write([]byte(nextDt))
ну и везде в подобных местах

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +const (
лучше или в начале файла или поближе к месту использования

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +		_, err = repo.Repo.Exec("DELETE FROM scheduler WHERE id = :id", sql.Named("id", task.ID))
а почему DeleteTask не переиспользовал?

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	if _, err = time.Parse("20060102", task.Date); err != nil {
20060102  вынести в константу и везде использовать

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	row := repo.Repo.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше явно поля указывать чем *

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	fmt.Println(result)
лишнее логирование стоит убрать - логировать лучше только ошибки 

и мб на уровне выше

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +		fmt.Println(err)
тут ошибку скрыл - лучше вернуть

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +			continue
тут продолжать не стоит с разу вернуть ошибку

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	fmt.Println(date, "2")
что-то странное - стоит убрать

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	fmt.Println(date, "2")
для дебага есть дебагер - принтами не очень удобно это делать

2024-10-21 22:13 UTC, dirtymew commented on repository/repo.go
> +	if date.Before(time.Now().Truncate(24 * time.Hour)) {
лучше порефакторить - if if else - не очень красивая конструкция

2024-10-23 17:43 UTC, mkrshv commented on repository/repo.go
> +		_, err = repo.Repo.Exec("DELETE FROM scheduler WHERE id = :id", sql.Named("id", task.ID))
По очереди выполнения в задании удаление задачи было последним, поэтому на тот момент еще не было написано)

2024-11-03 09:55 UTC, merged